'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {Search} from 'lucide-react';
import {SiteHeader} from '@/components/site-header';
import {ecosystemApps,ecosystemCategories} from '@/lib/ecosystem-apps';

const statusRank={integrated:0,data:1,next:2,discover:3} as const;
const featuredRank=['Perpl','Kuru','Uniswap','Relay','Dynamic','Envio'];
const statusLabel={integrated:'Live integration',data:'Live data',next:'Next integration',discover:'Discover'} as const;

export default function AppsPage(){const [query,setQuery]=useState('');const [category,setCategory]=useState('All');const filtered=useMemo(()=>ecosystemApps.filter(app=>(category==='All'||app.category===category)&&`${app.name} ${app.category} ${app.description}`.toLowerCase().includes(query.toLowerCase())).sort((first,second)=>{const difference=statusRank[first.status]-statusRank[second.status];if(difference!==0)return difference;const firstFeatured=featuredRank.indexOf(first.name);const secondFeatured=featuredRank.indexOf(second.name);if(firstFeatured!==-1||secondFeatured!==-1)return(firstFeatured===-1?Number.MAX_SAFE_INTEGER:firstFeatured)-(secondFeatured===-1?Number.MAX_SAFE_INTEGER:secondFeatured);return first.name.localeCompare(second.name)}),[query,category]);const liveCount=ecosystemApps.filter(app=>app.status==='integrated'||app.status==='data').length;return <div className="directory-page"><SiteHeader/><main><section className="page-hero"><div className="section-kicker">MONAD APP DIRECTORY</div><h1>Explore the ecosystem.<br/><span>Talk to it through MOT.</span></h1><p>Start with the apps already connected to MOTBOT, then discover the wider Monad ecosystem and the integrations coming next.</p></section><section className="directory-tools"><label><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search apps, categories or use cases…"/></label><div>{ecosystemCategories.map(item=><button className={category===item?'active':''} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div></section>{category==='All'&&!query&&<div className="directory-section-head"><div><span>LIVE ON MOTBOT</span><h2>Integrated apps come first.</h2></div><p>{liveCount} working integrations available now</p></div>}<section className="directory-grid">{filtered.map(app=>{const isLive=app.status==='integrated'||app.status==='data';return <article className={isLive?'app-card-live':undefined} key={app.name}><div className="app-monogram">{app.name.slice(0,2).toUpperCase()}</div><span className={`app-state ${app.status}`}>{statusLabel[app.status]}</span><h2>{app.name}</h2><small>{app.category}</small><p>{app.description}</p>{isLive?<Link href="/chat">Use with MOT →</Link>:<span className="directory-note">Integration not active yet</span>}</article>})}</section>{!filtered.length&&<p className="no-results">No apps match that search.</p>}</main></div>}
