import Link from 'next/link';
import {ArrowUp,Blocks,MessageSquare,Mic,Sparkles} from 'lucide-react';
import {SiteHeader} from '@/components/site-header';
import {ecosystemApps} from '@/lib/ecosystem-apps';

const motionApps=['PERPL','LEVR','KURU','UNISWAP','FASTLANE','RELAY','OPENSEA','LUMITERRA','PINGME','FARCASTER','NAD.FUN','NADRADAR'];
export default function Home(){return <div className="super-site"><SiteHeader/>
  <main>
    <section className="super-hero">
      <div className="super-glow"/><div className="super-copy"><div className="eyebrow"><span className="live-dot"/> THE CONVERSATIONAL LAYER FOR MONAD</div><h1>One conversation.<br/><span>The whole Monad ecosystem.</span></h1><p>Discover and interact with apps across Monad through one intelligent interface. Type it, say it, and let MOT guide the action.</p><div className="hero-actions"><Link className="primary-cta" href="/chat">Talk to MOT <ArrowUp size={17}/></Link><Link className="secondary-cta" href="/apps">Explore apps</Link></div><div className="super-stats"><span><strong>{ecosystemApps.length}+</strong> ecosystem apps</span><span><strong>Voice + text</strong> one interface</span><span><strong>PERPL</strong> live integration</span></div></div>
      <div className="ecosystem-orbit" aria-label="Monad ecosystem apps"><div className="orbit-core"><span>m</span><small>ASK MOT</small></div>{motionApps.slice(0,8).map((name,index)=><span className={`orbit-app orbit-${index+1}`} key={name}>{name}</span>)}</div>
    </section>
    <section className="app-ticker" aria-label="Featured Monad apps"><div>{[...motionApps,...motionApps].map((name,index)=><span key={`${name}-${index}`}>{name}<i>◆</i></span>)}</div></section>
    <section className="super-intro"><div className="section-kicker">BEYOND A SINGLE APP</div><div className="section-heading"><h2>Monad is growing. Your interface should stay simple.</h2><p>MOTBOT is designed as the conversational front door to trading, staking, payments, games, social apps, collectibles and whatever comes next.</p></div><div className="super-features"><article><MessageSquare/><h3>Say what you want</h3><p>Ask a question or describe an action in natural language.</p></article><article><Blocks/><h3>MOT finds the route</h3><p>The right Monad integration is selected without making you learn every interface.</p></article><article><Sparkles/><h3>Review, then act</h3><p>MOT explains the action and keeps execution under your control.</p></article></div></section>
    <section className="integration-stage"><div><div className="section-kicker">INTEGRATION STATUS</div><h2>Starting with one.<br/>Built to connect many.</h2><p>PERPL execution works today. The next integrations will expand MOT into swaps, sports, payments, analytics and more.</p><Link className="secondary-cta" href="/roadmap">See the integration roadmap</Link></div><div className="status-stack"><div className="status-card live"><span>LIVE NOW</span><strong>PERPL</strong><p>Prices, position visibility and confirmed testnet execution.</p></div><div className="status-card"><span>NEXT WAVE</span><strong>LEVR · KURU · UNISWAP · RELAY</strong><p>Selected by usefulness, technical access and ecosystem reach.</p></div><div className="status-card"><span>DISCOVER</span><strong>{ecosystemApps.length}+ apps</strong><p>Browse the wider Monad ecosystem from one organized directory.</p></div></div></section>
    <section className="voice-callout"><Mic/><div><span>VOICE OR TEXT</span><h2>Your words become the interface.</h2></div><Link className="primary-cta" href="/chat">Start a conversation <ArrowUp size={17}/></Link></section>
  </main><footer className="site-footer"><Link className="brand" href="/"><span className="brandmark">m</span>MOTBOT</Link><span>The conversational super-app for Monad.</span><span>Testnet first · User controlled</span></footer>
  </div>}
