'use client';
import {useEffect,useRef,useState} from 'react';
import {PerplSetup} from '@/components/perpl-setup';
import {ArrowUp, Mic, Wallet, Settings2, MessageSquare, ShieldCheck, Activity, Bell, ExternalLink, Square, X} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
type Message={role:'mot'|'user';text:string;generationUrl?:string};
const initial:Message={role:'mot',text:"Hey, I’m MOT. Ask about a market, talk through a trading idea, or tell me what you want to do. You can type or use your voice. This early version previews instructions; it cannot execute trades yet."};
const defaults={slOn:true,sl:50,tpOn:false,tp:100,maxMargin:10,maxLeverage:10,totalMargin:50,expiry:24,notification:'app'};
export default function Home(){
 const [aiReady,setAiReady]=useState(false);const [aiConsent,setAiConsent]=useState(false);
 useEffect(()=>{let active=true;fetch('/api/mot/chat').then(r=>r.json()).then(d=>{if(active)setAiReady(d.aiConfigured===true);}).catch(()=>{});return()=>{active=false;};},[]);
 const [messages,setMessages]=useState<Message[]>([initial]);const [input,setInput]=useState('');const [wallet,setWallet]=useState('');const [notice,setNotice]=useState('');const [settings,setSettings]=useState(false);const [coming,setComing]=useState('');const [prefs,setPrefs]=useState(defaults);const [loaded,setLoaded]=useState(false);const [listening,setListening]=useState(false);const [busy,setBusy]=useState(false);const [markets,setMarkets]=useState<any[]>([]);const [marketError,setMarketError]=useState('');const end=useRef<HTMLDivElement>(null);const recognition=useRef<any>(null);
 useEffect(()=>{try{const p=localStorage.getItem('mot.preferences');if(p)setPrefs({...defaults,...JSON.parse(p)});}catch{}setLoaded(true);return ()=>recognition.current?.abort();},[]);
 useEffect(()=>{if(loaded)localStorage.setItem('mot.preferences',JSON.stringify(prefs));},[prefs,loaded]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages]);
 useEffect(()=>{const provider=(window as any).ethereum;if(!provider)return;const changed=(a:string[])=>setWallet(a[0]||'');provider.on?.('accountsChanged',changed);return()=>provider.removeListener?.('accountsChanged',changed);},[]);
 useEffect(()=>{let active=true;async function fetchMarkets(){try{const r=await fetch('/api/markets');const d:any=await r.json();if(!r.ok)throw Error(d.error);if(active){setMarkets(d.markets||[]);setMarketError('');}}catch{if(active)setMarketError('PERPL market data is unavailable. Prices are not estimated.');}}fetchMarkets();const timer=setInterval(fetchMarkets,30000);return()=>{active=false;clearInterval(timer);};},[]);
 async function connect(){try{const e=(window as any).ethereum;if(!e){setNotice('Open MOTBOT in a wallet-enabled browser or install a wallet extension such as MetaMask.');return;}const a=await e.request({method:'eth_requestAccounts'});setWallet(a[0]||'');setNotice('Wallet connected. This does not yet authorize trading.');}catch{setNotice('Wallet connection was declined or unavailable. You can try again.');}}
 function voice(){if(listening){recognition.current?.stop();setListening(false);return;}const C=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!C){setNotice('Voice input is unavailable in this browser. You can always type your command.');return;}const r=new C();recognition.current=r;r.lang='en-US';r.interimResults=false;r.onresult=(e:any)=>setInput(e.results[0][0].transcript);r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setNotice('Could not capture your voice. Check microphone permissions or type instead.');};try{r.start();setListening(true);}catch{setNotice('Microphone could not start. Please try again.');}}
 async function send(text=input){if(!text.trim()||busy)return;if(text.length>3000){setNotice('Please keep each message under 3,000 characters.');return;}const history=messages.slice(1).slice(-10).map(m=>({role:m.role==='mot'?'assistant':'user',content:m.text.slice(0,3000)}));while(history.reduce((n,m)=>n+m.content.length,0)>10000)history.shift();setInput('');setBusy(true);setMessages(m=>[...m,{role:'user',text}]);try{const r=await fetch('/api/mot/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history,settings:prefs,wallet:!!wallet,aiConsent})});const d:any=await r.json();setMessages(m=>[...m,{role:'mot',text:d.reply||'I could not process that request. Please try again.',generationUrl:typeof d.generationUrl==='string'&&/^\/chat\/[a-f0-9-]+$/.test(d.generationUrl)?d.generationUrl:undefined}]);}catch{setMessages(m=>[...m,{role:'mot',text:'Connection interrupted. No trade was submitted.'}]);}finally{setBusy(false);}}
 useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const controller=new AbortController();try{Promise.resolve(c.registerTool({name:'open_trading_settings',description:'Open the visible MOTBOT trading settings dialog. Does not authorize or execute trades.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No arguments accepted');setSettings(true);return {opened:true};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[]);
 const set=(key:string,value:any)=>setPrefs(p=>({...p,[key]:value}));
 return <div className="app-shell"><header className="topbar site-topbar"><a className="brand" href="#top" aria-label="MOTBOT home"><span className="brandmark">m</span>MOTBOT<span className="network">ON MONAD</span></a><nav className="site-nav" aria-label="Main navigation"><a href="#about">About</a><a href="#how-it-works">How it works</a><a href="#integrations">Integrations</a><a href="#roadmap">Roadmap</a><a href="#blog">Blog <small>Upcoming</small></a></nav><button className="wallet-button" onClick={connect}><Wallet size={17}/>{wallet?`${wallet.slice(0,6)}…${wallet.slice(-4)}`:'Connect wallet'}</button></header>
 <section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> Conversational finance on Monad</div><h1>Trade at the speed of conversation.</h1><p>MOTBOT makes perpetual trading feel as natural as talking to a friend. Ask questions, speak your intent, and stay in control of every instruction.</p><div className="hero-actions"><a className="primary-cta" href="#trade">Launch MOTBOT <ArrowUp size={17}/></a><a className="secondary-cta" href="#how-it-works">See how it works</a></div><div className="hero-proof"><span><ShieldCheck size={16}/> User-directed execution</span><span><Mic size={16}/> Voice or text commands</span><span><Activity size={16}/> Built for Monad</span></div><div className="hero-integrations"><span>Starting with <strong>PERPL</strong></span><i>·</i><span>LEVR <small>Incoming</small></span><i>·</i><span>Polymarket <small>Incoming</small></span></div></div><div className="hero-card"><div className="hero-card-top"><span className="mini-label">MOTBOT / PERPL</span><span className="status-pill">Early access</span></div><div className="hero-orb">m</div><p>“Short BTC with $10 at 10x.”</p><div className="hero-response"><span>MOT</span><strong>Instruction understood. Ready when you are.</strong></div></div></section>
 <section className="intro-section white-section" id="about"><div className="section-kicker">THE MOTBOT APPROACH</div><div className="section-heading"><h2>A calmer interface for complex markets.</h2><p>MOTBOT brings market context, risk preferences, and execution controls into one clear conversation — without hiding the important details.</p></div><div className="feature-grid"><article><span className="feature-icon"><MessageSquare size={20}/></span><h3>Talk naturally</h3><p>Type or use your voice to ask questions and describe the trade you want.</p></article><article><span className="feature-icon"><ShieldCheck size={20}/></span><h3>You stay in control</h3><p>MOT can analyse and prepare an instruction, but only acts when you explicitly tell it to.</p></article><article><span className="feature-icon"><Bell size={20}/></span><h3>Built for follow-through</h3><p>Defaults, alerts, and conditional instructions help you manage trades after the conversation.</p></article></div></section>
 <section className="how-section" id="how-it-works"><div className="section-kicker">HOW IT WORKS</div><div className="section-heading"><h2>From thought to instruction in three steps.</h2><p>A simple path for traders who want less friction and more clarity.</p></div><div className="steps-grid"><div><span>01</span><h3>Connect</h3><p>Connect a new wallet and set your trading limits, default stop-loss, take-profit, and alert preferences.</p></div><div><span>02</span><h3>Talk</h3><p>Ask for a market price, discuss an idea, or give MOT a precise trade instruction by voice or text.</p></div><div><span>03</span><h3>Review and act</h3><p>MOT shows the instruction clearly before the trade is submitted. Your rules stay visible throughout.</p></div></div></section>
 <section className="trade-banner" id="trade"><div><div className="section-kicker">YOUR WORKSPACE</div><h2>Meet MOT where the work happens.</h2><p>Use the live workspace below to explore the conversation-first trading experience.</p></div><a className="primary-cta light" href="#command">Start a conversation <ArrowUp size={17}/></a></section>
 <div className="workspace"><aside className="sidebar"><div className="side-title">YOUR WORKSPACE</div><button className="side-link selected" onClick={()=>document.getElementById('command')?.focus()}><MessageSquare size={18}/>Talk to MOT</button><button className="side-link" onClick={()=>setSettings(true)}><Settings2 size={18}/>Trading settings</button><div className="side-divider"/><div className="side-title">EXECUTION</div><div className="execution-note"><ShieldCheck size={21}/><strong>You give the instruction.</strong><p>MOT never opens a trade from its own analysis.</p></div><div className="sidebar-bottom"><span className="version">EARLY ACCESS · TESTNET FIRST</span><a href="https://docs.perpl.xyz/resources/for-developers" target="_blank" rel="noreferrer">PERPL documentation <ExternalLink size={14}/></a></div></aside>
 <main className="conversation"><div className="conversation-top"><div><h1>Talk to MOT</h1><p>Your trading workspace. In your own words.</p></div><button className="icon-button" aria-label="Open trading settings" onClick={()=>setSettings(true)}><Settings2 size={20}/></button></div><div className="availability"><Activity size={16}/><span>Trading setup pending · Orders cannot execute yet</span></div>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notification"><X size={16}/></button></div>}
 <div className="ai-status">{aiReady?<label><input type="checkbox" checked={aiConsent} onChange={e=>setAiConsent(e.target.checked)}/> Enable AI conversation. Messages, recent conversation and preferences are sent to the AI provider and saved privately. Never enter secrets.</label>:<span>Live prices and instruction previews available · AI activation pending</span>}</div>
 <div className="messages" aria-live="polite">{messages.length===1&&<div className="welcome"><span className="mot-emblem">m</span><h2>What’s your next move?</h2><p>A conversation is a good place to start.</p></div>}{messages.map((m,i)=><div key={i} className={`message ${m.role}`}><span className="message-label">{m.role==='mot'?'MOT':'YOU'}</span><p>{m.text}</p>{m.generationUrl&&<a href={m.generationUrl}>View saved response</a>}</div>)}{busy&&<div className="message mot"><span className="message-label">MOT</span><p>Checking your request…</p></div>}<div ref={end}/></div>
 {messages.length===1&&<div className="suggestions">{['What is the price of Bitcoin?','Short BTC with $10 at 10x','Explain margin and leverage'].map(s=><button key={s} onClick={()=>send(s)}>{s}<ArrowUp size={14}/></button>)}</div>}
 <form className="composer" onSubmit={e=>{e.preventDefault();send();}}><textarea id="command" aria-label="Message MOT" placeholder={listening?'Listening… press stop when you finish':'Ask a question or give a trading instruction…'} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}} rows={2}/><div className="composer-bottom"><span><ShieldCheck size={14}/>Your wallet. Your instructions.</span><div><button type="button" className={`voice-button ${listening?'recording':''}`} onClick={voice} aria-label={listening?'Stop recording':'Start voice input'}>{listening?<Square size={17}/>:<Mic size={18}/>}</button><button className="send-button" aria-label="Send message" disabled={!input.trim()||busy}><ArrowUp size={20}/></button></div></div></form><p className="composer-hint">Voice or text, anytime. Voice commands appear here for you to send.</p></main>
 <aside className="market-panel"><div className="panel-title">MARKET WATCH <span>PERPL</span></div>{marketError?<div className="empty-market"><Activity size={24}/><p>{marketError}</p></div>:markets.length?markets.slice(0,4).map(m=><button className="market-row" key={m.symbol} onClick={()=>send(`What is the price of ${m.symbol}?`)}><span>{m.symbol}<small>Perpetual</small></span><strong>{m.price?`$${Number(m.price).toLocaleString(undefined,{maximumFractionDigits:2})}`:'—'}</strong></button>):<p className="muted">Loading PERPL markets…</p>}
 <section className="limits"><div className="panel-title">YOUR DEFAULTS<button aria-label="Edit defaults" onClick={()=>setSettings(true)}><Settings2 size={15}/></button></div><dl><div><dt>Margin per trade</dt><dd>≤ ${prefs.maxMargin}</dd></div><div><dt>Leverage</dt><dd>≤ {prefs.maxLeverage}x</dd></div><div><dt>Stop-loss</dt><dd>{prefs.slOn?`${prefs.sl}% of margin`:'Off'}</dd></div><div><dt>Take-profit</dt><dd>{prefs.tpOn?`${prefs.tp}% of margin`:'Off'}</dd></div></dl><p>Defaults apply to new trades. A trade-specific instruction overrides its corresponding default.</p></section>
 <PerplSetup wallet={wallet} connect={connect}/><section className="positions"><div className="panel-title">OPEN POSITIONS</div><div className="empty-positions"><Wallet size={25}/><h3>Trading not enabled</h3><p>Positions cannot be loaded until trading authorization is connected.</p></div></section><div className="referral-note">Referral registration will be added in a future update.</div></aside></div>
 <Dialog open={!!coming} onOpenChange={o=>{if(!o)setComing('');}}><DialogContent><DialogTitle>{coming}</DialogTitle><DialogDescription>Coming soon. The first MOTBOT integration focuses on PERPL perpetual trading. Orders are not routed to this platform yet.</DialogDescription></DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings-dialog"><DialogTitle>Trading settings</DialogTitle><DialogDescription>Choose your limits and defaults. These preferences do not grant trading authorization.</DialogDescription><div className="settings-fields">{[['Maximum margin per trade ($)','maxMargin'],['Maximum leverage (x)','maxLeverage'],['Maximum total open margin ($)','totalMargin'],['Conditional instruction expiry (hours)','expiry']].map(([label,key])=><label className="number-row" key={key}>{label}<input aria-label={label} type="number" min="1" max={key==='maxLeverage'?100:100000} value={(prefs as any)[key]} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=1&&n<=100000)set(key,n);}}/></label>)}<div className="setting-block"><label htmlFor="default-sl">Default stop-loss</label><Switch id="default-sl" checked={prefs.slOn} onCheckedChange={v=>set('slOn',v)}/><p>When off, no automatic loss protection is applied unless requested for a trade.</p>{prefs.slOn&&<label className="number-row">Loss as % of opening margin<input aria-label="Default stop loss percent" type="number" min="1" max="100" value={prefs.sl} onChange={e=>{const n=+e.target.value;if(n>0&&n<=100)set('sl',n);}}/></label>}</div><div className="setting-block"><label htmlFor="default-tp">Default take-profit</label><Switch id="default-tp" checked={prefs.tpOn} onCheckedChange={v=>set('tpOn',v)}/><p>Target profit as a percentage of each trade’s opening margin.</p>{prefs.tpOn&&<label className="number-row">Profit as % of opening margin<input aria-label="Default take profit percent" type="number" min="1" value={prefs.tp} onChange={e=>{const n=+e.target.value;if(n>0&&n<=100000)set('tp',n);}}/></label>}</div><label className="notification-choice">Alert delivery<Select value={prefs.notification} onValueChange={v=>set('notification',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="app">In-app only</SelectItem><SelectItem value="email">Email only</SelectItem><SelectItem value="both">Email and in-app</SelectItem></SelectContent></Select><span>Email delivery and background alerts are not active yet.</span></label></div><button className="save-button" onClick={()=>{setSettings(false);setNotice('Preferences saved on this device. Trading authorization is still pending.');}}>Save preferences</button></DialogContent></Dialog>
 <section className="intro-section white-section integrations-section" id="integrations"><div className="section-kicker">ONE HOME, MULTIPLE MARKETS</div><div className="section-heading"><h2>Starting with PERPL. Expanding with purpose.</h2><p>MOTBOT is designed as a single interface for the markets people already use — with each integration introduced carefully.</p></div><div className="integration-grid"><div className="integration-card active"><span>PERPL</span><strong>Perpetual trading</strong><small>Available first on Monad</small></div><div className="integration-card"><span>LEVR</span><strong>Sports betting</strong><small>Coming soon</small></div><div className="integration-card"><span>POLYMARKET</span><strong>Prediction markets</strong><small>Coming soon</small></div><div className="integration-card other-apps"><span>OTHER MONAD APPS</span><strong>More integrations</strong><small>Incoming</small></div></div></section>
 <section className="roadmap-section" id="roadmap"><div className="section-kicker">THE ROAD AHEAD</div><div className="section-heading"><h2>Built for the long term.</h2><p>MOTBOT is an evolving product, not a one-week interface.</p></div><div className="roadmap-list"><div><span className="roadmap-status current">Now</span><strong>Conversation-first PERPL workspace</strong><p>Wallet connection, market context, voice input, settings, and safe instruction previews.</p></div><div><span className="roadmap-status next">Next</span><strong>Authorized execution and alerts</strong><p>PERPL account enrollment, conditional orders, notifications, and position management.</p></div><div><span className="roadmap-status future">Later</span><strong>LEVR, Polymarket, and Telegram</strong><p>More markets and familiar places to talk to MOT, with the same safety controls.</p></div></div></section>
 <section className="blog-strip white-section" id="blog"><div><div className="section-kicker">MOTBOT JOURNAL</div><h2>Ideas, market notes, and product updates.</h2><p>The MOTBOT blog is coming soon.</p></div><span className="upcoming-badge">UPCOMING</span></section><footer className="site-footer"><a className="brand" href="#top"><span className="brandmark">m</span>MOTBOT</a><span>Conversational finance on Monad</span><span>Built for the next market interface.</span></footer></div>;
}
